### ISSUE TITLE
Gnome 45 compatibility

### ISSUE THREAD

**Issue by Roblex09** [RosGtHub/Hide-dock-in-overview#1]
Hi!

Can you make it compatible with Gnome 45, please?

**Comment by RosGtHub** [comment]
Hi, certainly. I'll update it shortly. Thank you for asking!

**Comment by RosGtHub** [comment]
I have just uploaded the extension. It will be available soon and will perform even better. I'll close this issue when it has been reviewed.

**Comment by Roblex09** [comment]
Thanks a lot! It's working perfectly, but I can't help noticing that the Dash appears a bit too quickly after I exit the overview. Is there a way to introduce a slight delay before the Dash reappears?

**Comment by RosGtHub** [comment]
Yes, of course. Here's the process:
 
Go to -> ~/.local/share/gnome-shell/extensions/hide-dock-in-overview@roslax
Open the file extension.js and change the function onOverviewDeactivated() with this code:

```
function onOverviewDeactivated() {
  setTimeout(() => {
    Main.overview.dash.show();
  }, 1000);
}
```
By employing this approach, the dock's display will be delayed for one second upon transitioning away from the overview. 
If you wish to alter the delay, simply modify the value 1000 to reflect the desired wait time in milliseconds.

**Comment by RosGtHub** [comment]
I might consider implementing some sort of animation while doing this. It would be fun and interesting.

**Comment by Roblex09** [comment]
Thanks once more! It's working exactly as I wanted it to. I plan to incorporate some form of animation, but I'm relatively new to programming.

**Comment by RosGtHub** [comment]
Don't worry. I'm a high school student, and I'm not as professional as you might think. You can see it from my quirky commits. Let's keep moving forward! and most importantly, keep learning! i'm trying to be more patient and learn alot of things. I hope to become a good developer one day.

**Comment by Roblex09** [comment]
Awesome mindset! Keep learning and moving forward. You're doing great!
