### ISSUE TITLE
Gnome 43.9 compatibility

### ISSUE THREAD

**Issue by Francewhoa** [RosGtHub/Hide-dock-in-overview#2]
This is a suggestion to make this extension compatible with Gnome 43.9

Both me and the Ubertus.Org team would be happy, as volunteer, to contribute testing and documentation, if needed.

For those not familiar with Debian. Its most recent release from December 2023 shipped with GNOME 43.9. This release code is Debian 12 Bookworm.

**Comment by RosGtHub** [comment]
Hi there,

I wanted to first thank you for opening an issue regarding the compatibility with Gnome 43.9. I really appreciate your interest and willingness to contribute!

I'm excited to announce that the package is now ready for testing with Gnome 43.9! You can download it directly clicking the link down below: 

[hide-dock-in-overview@roslax.zip](https://github.com/RosGtHub/Hide-dock-in-overview/files/14303793/hide-dock-in-overview%40roslax.zip)

For installation instructions, check out the steps on the main page.

Once you've had a chance to try it, please let me know how it performs and if you encounter any issues.

Thanks again and best regards,
Roslax

UPDATE: You can now install it through the gnome extentions manager or website. Feel free to open another issue if you need it.

**Comment by Francewhoa** [comment]
Thanks @RosGtHub :) 

This is to confirm that this successfully works with Gnome 43.9. The orange number 1 below shows this.

![Screenshot-266](https://github.com/RosGtHub/Hide-dock-in-overview/assets/119942/3ca4651a-51c1-4c24-913f-a7264cff85cb)

![Screenshot-267](https://github.com/RosGtHub/Hide-dock-in-overview/assets/119942/9275f202-c096-4cb8-a48e-909bfbcff4f2)
