### ISSUE TITLE
Dock appears for a second when going back to desktop

### ISSUE THREAD

**Issue by momoRaza** [RosGtHub/Hide-dock-in-overview#3]
Great extension, but for some reason when I switch back from overview to desktop, the dock appears for a second.
here is what I mean:
https://streamable.com/pmrdee

**Comment by RosGtHub** [comment]
Hi, thank you for reaching out and for providing the helpful video! Tomorrow i'll probably fix that.  

Best regards,
Roslax

**Comment by momoRaza** [comment]
> Hi, thank you for reaching out and for providing the helpful video! Tomorrow i'll probably fix that.
> 
> Best regards, Roslax

great!, Thank you!

**Comment by RosGtHub** [comment]
Morning, i just fixed that.

Here's the file to extract in your extension folder:
[hide-dock-in-overview@roslax.zip](https://github.com/RosGtHub/Hide-dock-in-overview/files/14627115/hide-dock-in-overview%40roslax.zip)

Just remove the old one and then extract the .zip file into the extension folder. Once you've done it reboot and it should work.
Let me know if you've any issues.

**Comment by momoRaza** [comment]
Thank you, worked like a charm. I should have thought of that adding a 200ms delay would work :)
Appreciate it!

**Comment by RosGtHub** [comment]
Happy to read that! I'd be incredibly grateful if you considered starring the project on GitHub. It really helps with visibility and shows support for the work involved.  The release for Gnome versions 43, 44, and 45 is just around the corner – I just committed the changes, and they're awaiting review.

Best regards, 
Roslax

**Comment by momoRaza** [comment]
Absolutely! done

**Comment by RosGtHub** [comment]
Update: Unfortunately, the extension was recently rejected due to the use of the setTimeout() function, which doesn't comply with GNOME's extension guidelines.

I'm working on revising the code to ensure it adheres to these guidelines. You'll receive another notification once a new version is available for download.

In the meantime, the current version of the extension should still be functional. However, if you encounter any issues, please don't hesitate to let me know.

Thank you for your understanding and patience.

Regards,

Roslax

**Comment by momoRaza** [comment]
no problem, thanks for your effort and work.

**Comment by RosGtHub** [comment]
Hi, i just uploaded the extension. Soon it will be reviewed. I'll let you know when it's available.

**Comment by RosGtHub** [comment]
Hi happy easter, today i will fix all the issues about the new update of the extension. I'll let you know when it will be available again. Sorry for the unfortunate if you had already updated. (It is possible to use setTimeOut()  there was a misunderstanding from myself i only did It in the wrong way)

[EDIT]
Done!
