### ISSUE TITLE
Unsupported on Gnome 46

### ISSUE THREAD

**Issue by NewsonUpreti** [RosGtHub/Hide-dock-in-overview#5]
I just upgraded to official release of Fedora 40 which ships gnome 46.1, All the other extensions are working properly except this one. I tried some troubleshooting like reboot, reinstall extension, login and out, trying on another computer. But didn't work.

**Comment by RosGtHub** [comment]
> I just upgraded to official release of Fedora 40 which ships gnome 46.1, All the other extensions are working properly except this one. I tried some troubleshooting like reboot, reinstall extension, login and out, trying on another computer. But didn't work.
> 

Hi there, 

The extension supports only gnome 43,44 and 45 at the moment.That's why It doesn't work. I'll update it soon, maybe today or tomorrow.

Regards, 
Roslax

**Comment by NewsonUpreti** [comment]
?

**Comment by RosGtHub** [comment]
> ?

Hi, yesterday was a festival day.  Can you test the extension for gnome 46?
[hide-dock-in-overview@roslax.zip](https://github.com/RosGtHub/Hide-dock-in-overview/files/15137871/hide-dock-in-overview%40roslax.zip)
They shouldn't have modified the extension.js and metadata.json. So, should work as it is just changing the key "version" to the value 46 in the metadata.json. Let me know!
Regards,
Roslax
